"""
PrintChakra Backend - OCR Extraction Routes

Text extraction endpoints using PaddleOCR.
"""

import os
import logging
import json
import time
from flask import jsonify, request, send_file
from werkzeug.utils import secure_filename
from app.features.document.ocr.routes import ocr_bp
from app.core.middleware.cors import create_options_response
from app.core.config import get_data_dirs

logger = logging.getLogger(__name__)


def _as_ocr_response(filename: str, result: dict) -> dict:
    """Normalize OCR payload into frontend OCRResponse shape."""
    ocr_result = result.get("ocr_result")
    success = bool(result.get("success"))
    if not isinstance(ocr_result, dict):
        text = result.get("text", "") or ""
        ocr_result = {
            "raw_results": [],
            "structured_units": [],
            "full_text": text,
            "derived_title": text.splitlines()[0][:120] if text else "",
            "confidence_avg": 0.0,
            "word_count": len([w for w in text.replace("\n", " ").split(" ") if w.strip()]),
            "timestamp": "",
            "processing_time_ms": 0,
            "image_dimensions": [0, 0],
        }

    return {
        "success": success,
        "filename": filename,
        "ocr_result": ocr_result,
        "ocr_ready": bool(ocr_result.get("word_count", 0) > 0),
        "error": result.get("error"),
    }


def _load_saved_pipeline_ocr(filename: str) -> dict | None:
    """Load OCR output generated by the 12-step phone pipeline."""
    dirs = get_data_dirs()
    stem = os.path.splitext(filename)[0]
    json_path = os.path.join(dirs["OCR_DATA_DIR"], f"{stem}_ocr.json")
    txt_candidates = [
        os.path.join(dirs["TEXT_DIR"], f"{stem}.txt"),
        os.path.join(dirs["TEXT_DIR"], f"processed_{stem}.txt"),
    ]

    saved_result = None
    if os.path.isfile(json_path):
        try:
            with open(json_path, "r", encoding="utf-8") as f:
                saved_result = json.load(f)
        except Exception as exc:
            logger.warning(f"Failed to read saved OCR JSON for {filename}: {exc}")

    text = ""
    for path in txt_candidates:
        if os.path.isfile(path):
            with open(path, "r", encoding="utf-8") as f:
                text = f.read()
            break

    if not saved_result and not text.strip():
        return None

    if not isinstance(saved_result, dict):
        saved_result = {}

    full_text = saved_result.get("full_text") or text
    raw_results = saved_result.get("raw_results") or []
    structured_units = saved_result.get("structured_units") or [
        {"text": line.strip(), "type": "paragraph"}
        for line in full_text.splitlines()
        if line.strip()
    ]
    ocr_result = {
        "raw_results": raw_results,
        "structured_units": structured_units,
        "full_text": full_text,
        "derived_title": saved_result.get("derived_title") or (full_text.splitlines()[0][:120] if full_text else ""),
        "confidence_avg": float(saved_result.get("confidence_avg", 0.0)),
        "word_count": saved_result.get("word_count")
        or len([word for word in full_text.replace("\n", " ").split(" ") if word.strip()]),
        "timestamp": saved_result.get("timestamp", ""),
        "processing_time_ms": saved_result.get("processing_time_ms", 0),
        "image_dimensions": saved_result.get("image_dimensions", [0, 0]),
        "engine": saved_result.get("engine", "enhanced_12_step"),
    }
    return {
        "success": True,
        "filename": filename,
        "ocr_result": ocr_result,
        "text": full_text,
    }


def _find_document_path(filename: str) -> str | None:
    """Resolve a document path using the app's configured storage directories."""
    dirs = get_data_dirs()
    candidate_paths = [
        os.path.join(dirs["UPLOAD_DIR"], filename),
        os.path.join(dirs["PDF_DIR"], filename),
        os.path.join(dirs["PROCESSED_DIR"], filename),
        os.path.join(dirs["CONVERTED_DIR"], filename),
    ]
    return next((path for path in candidate_paths if os.path.isfile(path)), None)


@ocr_bp.route("/extract", methods=["POST", "OPTIONS"])
def extract_text():
    """Extract text from a document using OCR."""
    if request.method == "OPTIONS":
        return create_options_response()
    
    try:
        # Handle file upload or document ID
        if "file" in request.files:
            file = request.files["file"]
            if file.filename == "":
                return jsonify({"success": False, "error": "No file selected"}), 400
            
            # Save temporarily
            import uuid
            temp_filename = f"ocr_temp_{uuid.uuid4().hex}_{secure_filename(file.filename)}"
            temp_path = os.path.join(get_data_dirs()["UPLOAD_DIR"], temp_filename)
            os.makedirs(os.path.dirname(temp_path), exist_ok=True)
            file.save(temp_path)
            document_path = temp_path
        
        else:
            data = request.get_json() or {}
            document_id = data.get("document_id")
            
            if not document_id:
                return jsonify({"success": False, "error": "No document provided"}), 400
            
            # Find document
            filename = secure_filename(document_id)
            document_path = _find_document_path(filename)
            
            if not document_path:
                return jsonify({"success": False, "error": "Document not found"}), 404
        
        # Get options
        language = request.form.get("language", "en") if "file" in request.files else (request.get_json() or {}).get("language", "en")
        use_ollama = request.form.get("use_ollama", "true").lower() == "true" if "file" in request.files else (request.get_json() or {}).get("use_ollama", True)
        
        # Perform OCR
        result = perform_ocr(document_path, language=language, use_ollama=use_ollama)
        
        if result.get("success"):
            # Save result
            ocr_results_dir = get_data_dirs()["TEXT_DIR"]
            os.makedirs(ocr_results_dir, exist_ok=True)
            
            import uuid
            result_filename = f"ocr_{uuid.uuid4().hex}.txt"
            result_path = os.path.join(ocr_results_dir, result_filename)
            
            with open(result_path, "w", encoding="utf-8") as f:
                f.write(result.get("text", ""))
            
            result["result_file"] = result_filename
            result["result_path"] = result_path
            
            logger.info(f"[OK] OCR completed for: {os.path.basename(document_path)}")
        
        response_name = os.path.basename(document_path)
        return jsonify(_as_ocr_response(response_name, result))
    
    except Exception as e:
        logger.error(f"OCR extraction error: {e}")
        return jsonify({"success": False, "error": str(e)}), 500


@ocr_bp.route("/extract/<doc_id>", methods=["GET", "OPTIONS"])
def extract_text_by_id(doc_id):
    """Extract text from a document by ID."""
    if request.method == "OPTIONS":
        return create_options_response()
    
    try:
        filename = secure_filename(doc_id)
        
        # Find document
        document_path = _find_document_path(filename)
        
        if not document_path:
            return jsonify({"success": False, "error": "Document not found"}), 404

        saved_result = _load_saved_pipeline_ocr(filename)
        if saved_result:
            return jsonify(_as_ocr_response(filename, saved_result))
        
        # Get options from query params
        language = request.args.get("language", "en")
        use_ollama = request.args.get("use_ollama", "true").lower() == "true"
        
        # Perform OCR
        result = perform_ocr(document_path, language=language, use_ollama=use_ollama)
        
        return jsonify(_as_ocr_response(filename, result))
    
    except Exception as e:
        logger.error(f"OCR extraction error: {e}")
        return jsonify({"success": False, "error": str(e)}), 500


@ocr_bp.route("/result/<result_id>", methods=["GET", "OPTIONS"])
def get_ocr_result(result_id):
    """Get OCR result by ID."""
    if request.method == "OPTIONS":
        return create_options_response()
    
    try:
        filename = secure_filename(result_id)
        result_path = os.path.join(get_data_dirs()["TEXT_DIR"], filename)
        
        if not os.path.exists(result_path):
            return jsonify({"success": False, "error": "Result not found"}), 404
        
        with open(result_path, "r", encoding="utf-8") as f:
            text = f.read()
        
        return jsonify({
            "success": True,
            "result_id": result_id,
            "text": text
        })
    
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@ocr_bp.route("/result/<result_id>/download", methods=["GET", "OPTIONS"])
def download_ocr_result(result_id):
    """Download OCR result as text file."""
    if request.method == "OPTIONS":
        return create_options_response()
    
    try:
        filename = secure_filename(result_id)
        result_path = os.path.join(get_data_dirs()["TEXT_DIR"], filename)
        
        if not os.path.exists(result_path):
            return jsonify({"success": False, "error": "Result not found"}), 404
        
        return send_file(
            result_path,
            as_attachment=True,
            download_name=filename
        )
    
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@ocr_bp.route("/status/<doc_id>", methods=["GET", "OPTIONS"])
def get_ocr_status_by_file(doc_id):
    """Get OCR-ready status for a given document ID."""
    if request.method == "OPTIONS":
        return create_options_response()

    try:
        filename = secure_filename(doc_id)
        stem = os.path.splitext(filename)[0]
        text_dir = get_data_dirs()["TEXT_DIR"]
        candidates = [
            os.path.join(text_dir, f"{stem}.txt"),
            os.path.join(text_dir, f"processed_{stem}.txt"),
            os.path.join(get_data_dirs()["OCR_DATA_DIR"], f"{stem}_ocr.json"),
        ]
        ready = any(os.path.isfile(path) for path in candidates)
        return jsonify({"filename": filename, "ocr_ready": ready})
    except Exception:
        return jsonify({"filename": doc_id, "ocr_ready": False})


def _make_bbox(points: list) -> dict:
    """Convert PaddleOCR polygon points to bbox object."""
    if not points:
        return {"x": 0, "y": 0, "width": 0, "height": 0, "points": []}
    xs = [float(p[0]) for p in points]
    ys = [float(p[1]) for p in points]
    return {
        "x": min(xs),
        "y": min(ys),
        "width": max(xs) - min(xs),
        "height": max(ys) - min(ys),
        "points": points,
    }


def _extract_json_from_llm_response(content: str) -> dict | None:
    """Try to extract JSON object from model output."""
    if not content:
        return None
    content = content.strip()
    try:
        return json.loads(content)
    except Exception:
        pass

    start = content.find("{")
    end = content.rfind("}")
    if start != -1 and end != -1 and end > start:
        candidate = content[start : end + 1]
        try:
            return json.loads(candidate)
        except Exception:
            return None
    return None


def parse_ocr_with_ollama(raw_text: str) -> dict:
    """Always attempt LLM parsing for structured OCR JSON."""
    model = os.getenv("OLLAMA_MODEL", "llama3.2")
    prompt = f"""You are an OCR post-processor.
Convert the OCR text below into STRICT JSON with this exact shape:
{{
  "derived_title": "short document title",
  "structured_units": [
    {{
      "text": "content",
      "type": "title|heading|paragraph|list_item|table_cell|footer|other"
    }}
  ],
  "full_text": "full cleaned text"
}}

Rules:
- Return ONLY valid JSON (no markdown, no explanation).
- Keep all important information from OCR text.
- If uncertain, still output best-effort JSON.

OCR text:
{raw_text}
"""
    try:
        import requests

        response = requests.post(
            "http://localhost:11434/api/generate",
            json={"model": model, "prompt": prompt, "stream": False},
            timeout=90,
        )
        if response.status_code != 200:
            return {"success": False, "error": f"Ollama returned {response.status_code}"}
        data = response.json()
        parsed = _extract_json_from_llm_response(data.get("response", ""))
        if not parsed:
            return {"success": False, "error": "LLM response was not valid JSON"}
        return {"success": True, "parsed": parsed, "model": model}
    except Exception as e:
        return {"success": False, "error": str(e)}


def _fallback_structured_units(raw_lines: list[str]) -> list[dict]:
    """Fallback unit classification when LLM JSON parse fails."""
    units = []
    for idx, line in enumerate(raw_lines):
        cleaned = line.strip()
        if not cleaned:
            continue
        line_type = "paragraph"
        if idx == 0 and len(cleaned) < 80:
            line_type = "title"
        elif cleaned.endswith(":"):
            line_type = "heading"
        elif cleaned.startswith(("-", "*", "•")):
            line_type = "list_item"
        units.append({"text": cleaned, "type": line_type})
    return units


def perform_ocr(image_path: str, language: str = "en", use_ollama: bool = True) -> dict:
    """Perform OCR and always post-process into structured JSON."""
    try:
        from app.modules.ocr.paddle_ocr import get_ocr_processor

        started = time.time()
        processor = get_ocr_processor(get_data_dirs()["OCR_DATA_DIR"])
        raw_results = []
        page_texts = []
        image_dimensions = [0, 0]

        def _normalize_processed_result(processed: object) -> dict:
            if hasattr(processed, "to_dict"):
                return processed.to_dict()
            if isinstance(processed, dict):
                return processed
            return {}

        def _merge_page_result(page_result: dict) -> None:
            if not page_result:
                return

            for entry in page_result.get("raw_results", []) or []:
                if isinstance(entry, dict):
                    raw_results.append(entry)

            full_text = (page_result.get("full_text", "") or "").strip()
            if full_text:
                page_texts.append(full_text)

            dims = page_result.get("image_dimensions") or [0, 0]
            if isinstance(dims, (list, tuple)) and len(dims) >= 2:
                try:
                    image_dimensions[0] = max(image_dimensions[0], int(dims[0]))
                    image_dimensions[1] = max(image_dimensions[1], int(dims[1]))
                except (TypeError, ValueError):
                    pass

        # Check if PDF - convert to images first
        ext = os.path.splitext(image_path)[1].lower()

        if ext == ".pdf":
            # Convert PDF pages to images
            try:
                import fitz
                from PIL import Image
                import tempfile

                doc = fitz.open(image_path)
                try:
                    for page_num in range(len(doc)):
                        page = doc.load_page(page_num)
                        pix = page.get_pixmap(matrix=fitz.Matrix(2, 2))  # 2x zoom for better OCR
                        image_dimensions[0] = max(image_dimensions[0], pix.width)
                        image_dimensions[1] = max(image_dimensions[1], pix.height)

                        # Convert to PIL Image
                        img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)

                        # Save to temp file for OCR
                        temp_path = None
                        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
                            img.save(tmp.name)
                            temp_path = tmp.name

                        try:
                            processed = processor.process_image(temp_path, lang=language, use_ollama=False)
                            _merge_page_result(_normalize_processed_result(processed))
                        finally:
                            if temp_path and os.path.exists(temp_path):
                                os.unlink(temp_path)
                finally:
                    doc.close()

            except ImportError:
                return {
                    "success": False,
                    "error": "PyMuPDF not available for PDF processing"
                }

        else:
            # Process image directly
            processed = processor.process_image(image_path, lang=language, use_ollama=False)
            _merge_page_result(_normalize_processed_result(processed))

        raw_text = "\n".join(page_texts).strip()
        if not raw_text and raw_results:
            raw_text = "\n".join(
                str(item.get("text", "")).strip()
                for item in raw_results
                if str(item.get("text", "")).strip()
            )

        raw_lines = [line.strip() for line in raw_text.split("\n") if line.strip()]
        llm_meta = {"used": False, "success": False, "error": None, "model": None}

        # Always attempt LLM JSON parsing when text exists.
        structured_units = []
        derived_title = raw_lines[0][:120] if raw_lines else ""
        full_text = raw_text
        if raw_text and use_ollama:
            llm_meta["used"] = True
            parsed = parse_ocr_with_ollama(raw_text)
            llm_meta["success"] = bool(parsed.get("success"))
            llm_meta["error"] = parsed.get("error")
            llm_meta["model"] = parsed.get("model")
            if parsed.get("success") and parsed.get("parsed"):
                parsed_obj = parsed["parsed"]
                structured_units = parsed_obj.get("structured_units") or []
                derived_title = (parsed_obj.get("derived_title") or derived_title)[:120]
                full_text = parsed_obj.get("full_text") or raw_text

        if not structured_units:
            structured_units = _fallback_structured_units(raw_lines)

        confidence_avg = (
            sum(float(r.get("confidence", 0)) for r in raw_results) / len(raw_results)
            if raw_results
            else 0.0
        )
        words = [w for w in full_text.replace("\n", " ").split(" ") if w.strip()]

        processing_time_ms = (time.time() - started) * 1000
        ocr_result = {
            "raw_results": raw_results,
            "structured_units": [
                {
                    "text": u.get("text", ""),
                    "type": u.get("type", "other"),
                    "bbox": u.get("bbox", {"x": 0, "y": 0, "width": 0, "height": 0}),
                    "confidence": float(u.get("confidence", confidence_avg or 0.75)),
                    "word_indices": u.get("word_indices", []),
                }
                for u in structured_units
                if isinstance(u, dict)
            ],
            "full_text": full_text,
            "derived_title": derived_title,
            "confidence_avg": confidence_avg,
            "word_count": len(words),
            "timestamp": "",
            "processing_time_ms": processing_time_ms,
            "image_dimensions": image_dimensions,
        }

        return {
            "success": True,
            "text": full_text,
            "raw_text": raw_text,
            "character_count": len(full_text),
            "line_count": len(full_text.split("\n")),
            "ocr_result": ocr_result,
            "llm": llm_meta,
        }

    except ImportError:
        return {
            "success": False,
            "error": "PaddleOCR not installed. Install with: pip install paddleocr paddlepaddle"
        }

    except Exception as e:
        return {
            "success": False,
            "error": str(e)
        }
